/**
 * Predefined list of Municipal Offices for Pinamungajan HR
 * Used for accurate Office/Department extraction from appointment documents
 */

export const MUNICIPAL_OFFICES = [
  "OFFICE OF THE MUNICIPAL MAYOR",
  "OFFICE OF THE MUNICIPAL MAYOR - TRAFFIC MANAGEMENT UNIT",
  "OFFICE OF THE MUNICIPAL MAYOR - CIVIL SECURITY UNIT",
  "OFFICE OF THE MUNICIPAL VICE MAYOR",
  "OFFICE OF THE SANGGUNIANG BAYAN",
  "OFFICE OF THE SANGGUNIANG BAYAN SECRETARY",
  "HUMAN RESOURCE MANAGEMENT OFFICE",
  "MUNICIPAL PLANNING AND DEVELOPMENT COORDINATOR OFFICE",
  "OFFICE OF THE MUNICIPAL BUDGET",
  "OFFICE OF THE MUNICIPAL ACCOUNTANT",
  "MUNICIPAL GENERAL SERVICES OFFICE",
  "OFFICE OF THE MUNICIPAL INTERNAL AUDIT SERVICE",
  "OFFICE OF THE MUNICIPAL CIVIL REGISTRAR",
  "OFFICE OF THE MUNICIPAL ASSESSOR",
  "MUNICIPAL HEALTH OFFICE",
  "MUNICIPAL SOCIAL WELFARE AND DEVELOPMENT OFFICE",
  "MUNICIPAL SOCIAL WELFARE AND DEVELOPMENT OFFICE - LOCAL YOUTH DEVELOPMENT OFFICE",
  "OFFICE OF THE MUNICIPAL TREASURER",
  "OFFICE OF THE MUNICIPAL TREASURER - OPERATION OF PUBLIC MARKET",
  "MUNICIPAL AGRICULTURE OFFICE",
  "MUNICIPAL TOURISM OFFICE",
  "OFFICE OF THE MUNICIPAL ENGINEER",
  "OFFICE OF THE MUNICIPAL ENGINEER - MUNICIPAL WATERWORKS MANAGEMENT SECTION",
  "MUNICIPAL ENVIRONMENT & NATURAL RESOURCES OFFICE",
  "MUNICIPAL VETERINARY OFFICE",
  "LOCAL DISASTER RISK REDUCTION AND MANAGEMENT OFFICE (LDRRMO)",
] as const;

export type MunicipalOffice = typeof MUNICIPAL_OFFICES[number];

/**
 * Find the best matching office from the predefined list
 * Uses fuzzy matching to handle OCR variations
 */
export function findMatchingOffice(text: string): string | null {
  const upperText = text.toUpperCase();
  
  // Priority 1: Exact match or contains full office name
  for (const office of MUNICIPAL_OFFICES) {
    const upperOffice = office.toUpperCase();
    if (upperText.includes(upperOffice)) {
      return office;
    }
  }
  
  // Priority 2: Partial match with key identifiers
  const officeKeywords: Record<string, string[]> = {
    "OFFICE OF THE MUNICIPAL MAYOR - TRAFFIC MANAGEMENT UNIT": ["TRAFFIC MANAGEMENT", "TMU"],
    "OFFICE OF THE MUNICIPAL MAYOR - CIVIL SECURITY UNIT": ["CIVIL SECURITY", "CSU"],
    "OFFICE OF THE MUNICIPAL VICE MAYOR": ["VICE MAYOR"],
    "OFFICE OF THE SANGGUNIANG BAYAN": ["SANGGUNIANG BAYAN", "SB"],
    "OFFICE OF THE SANGGUNIANG BAYAN SECRETARY": ["SANGGUNIANG BAYAN SECRETARY", "SB SECRETARY"],
    "HUMAN RESOURCE MANAGEMENT OFFICE": ["HUMAN RESOURCE", "HR", "HRMO"],
    "MUNICIPAL PLANNING AND DEVELOPMENT COORDINATOR OFFICE": ["PLANNING AND DEVELOPMENT", "MPDC"],
    "OFFICE OF THE MUNICIPAL BUDGET": ["MUNICIPAL BUDGET", "BUDGET OFFICE"],
    "OFFICE OF THE MUNICIPAL ACCOUNTANT": ["MUNICIPAL ACCOUNTANT", "ACCOUNTANT"],
    "MUNICIPAL GENERAL SERVICES OFFICE": ["GENERAL SERVICES", "MGSO"],
    "OFFICE OF THE MUNICIPAL INTERNAL AUDIT SERVICE": ["INTERNAL AUDIT", "MIAS"],
    "OFFICE OF THE MUNICIPAL CIVIL REGISTRAR": ["CIVIL REGISTRAR", "CR", "REGISTRAR"],
    "OFFICE OF THE MUNICIPAL ASSESSOR": ["MUNICIPAL ASSESSOR", "ASSESSOR"],
    "MUNICIPAL HEALTH OFFICE": ["HEALTH OFFICE", "MHO"],
    "MUNICIPAL SOCIAL WELFARE AND DEVELOPMENT OFFICE": ["SOCIAL WELFARE", "MSWDO"],
    "MUNICIPAL SOCIAL WELFARE AND DEVELOPMENT OFFICE - LOCAL YOUTH DEVELOPMENT OFFICE": ["YOUTH DEVELOPMENT", "LYDO"],
    "OFFICE OF THE MUNICIPAL TREASURER": ["MUNICIPAL TREASURER", "TREASURER"],
    "OFFICE OF THE MUNICIPAL TREASURER - OPERATION OF PUBLIC MARKET": ["PUBLIC MARKET", "MARKET OPERATION"],
    "MUNICIPAL AGRICULTURE OFFICE": ["AGRICULTURE OFFICE", "MAO"],
    "MUNICIPAL TOURISM OFFICE": ["TOURISM OFFICE", "MTO"],
    "OFFICE OF THE MUNICIPAL ENGINEER": ["MUNICIPAL ENGINEER", "ENGINEER"],
    "OFFICE OF THE MUNICIPAL ENGINEER - MUNICIPAL WATERWORKS MANAGEMENT SECTION": ["WATERWORKS", "WATER", "MWMS"],
    "MUNICIPAL ENVIRONMENT & NATURAL RESOURCES OFFICE": ["ENVIRONMENT", "MENRO"],
    "MUNICIPAL VETERINARY OFFICE": ["VETERINARY", "MVO"],
    "LOCAL DISASTER RISK REDUCTION AND MANAGEMENT OFFICE (LDRRMO)": ["DISASTER RISK", "LDRRMO"],
  };
  
  for (const [office, keywords] of Object.entries(officeKeywords)) {
    for (const keyword of keywords) {
      if (upperText.includes(keyword.toUpperCase())) {
        // Verify it's not a false positive by checking for "OFFICE" or "MUNICIPAL"
        if (upperText.includes("OFFICE") || upperText.includes("MUNICIPAL")) {
          return office;
        }
      }
    }
  }
  
  // Priority 3: Fuzzy match for common variations
  const fuzzyMatches: Record<string, string> = {
    "MUNICIPAL ENGINEER": "OFFICE OF THE MUNICIPAL ENGINEER",
    "MUNICIPAL ENGINEER - WATERWORKS": "OFFICE OF THE MUNICIPAL ENGINEER - MUNICIPAL WATERWORKS MANAGEMENT SECTION",
    "WATERWORKS MANAGEMENT": "OFFICE OF THE MUNICIPAL ENGINEER - MUNICIPAL WATERWORKS MANAGEMENT SECTION",
    "MWMS": "OFFICE OF THE MUNICIPAL ENGINEER - MUNICIPAL WATERWORKS MANAGEMENT SECTION",
  };
  
  for (const [pattern, office] of Object.entries(fuzzyMatches)) {
    if (upperText.includes(pattern.toUpperCase())) {
      return office;
    }
  }
  
  return null;
}

/**
 * Normalize office name from OCR text
 * Fixes common OCR errors and typos
 */
export function normalizeOfficeName(text: string): string {
  return text
    .replace(/OFTHE/gi, "OF THE")
    .replace(/OFFICEOFTHE/gi, "OFFICE OF THE")
    .replace(/MUNCIPAL/gi, "MUNICIPAL")
    .replace(/MUNICIPAL\s+MUNICIPAL/gi, "MUNICIPAL")
    .replace(/SANGGUNIANG\s+BAVAN/gi, "SANGGUNIANG BAYAN")
    .replace(/DEVELORMENT/gi, "DEVELOPMENT")
    .replace(/\s+/g, " ")
    .trim();
}
